name: Podman Crun test

concurrency:
  group: podman-crun-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  containerd:
    strategy:
      matrix:
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "FALSE"
          - name: "WasmEdge 0.9.1, Crun 1.4.5"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "FALSE"
          - name: "WasmEdge 0.10.0, Crun 1.5"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "FALSE"
          - name: "WasmEdge latest release, Crun master, ZH"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "TRUE"
          - name: "WasmEdge 0.9.1, Crun 1.4.5, ZH"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "TRUE"
          - name: "WasmEdge 0.10.0, Crun 1.5, ZH"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "TRUE"
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install podman, wasmedge and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
          ZH: ${{ matrix.zh }}
        run: |
          bash podman_crun/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION --zh=$ZH

      - name: Install podman, wasmedge and crun (latest version)
        if: ${{ matrix.latest }}
        env:
          ZH: ${{ matrix.zh }}
        run: |
          bash podman_crun/install.sh --zh=$ZH

      - name: Run container using podman
        run: |
          bash podman_crun/simple_wasi_application.sh

      - name: Display podman, crun and wasmedge version
        run: |
          podman --version
          crun --version
          wasmedge --version
